### ISSUE TITLE
Bad response body on OPTIONS request with CORS

### ISSUE THREAD

**Issue by lordent** [vsouza/JWT-Tornado#1]
U forgot about OPTIONS request with CORS requests. When u make GET request, your require_auth function return "Missing authorization", but if u make GET request with invalid "Authorization" header, server recieve OPTIONS request at first, then GET request. With current logic OPTIONS request check with require_auth, and response with 401 status, it is not right, because u get bad response body.
For fix it, u need to skip require_auth in _execute if request method is OPTIONS. U can check it with self.request.method for handler object. This check does not brake some logic and only adds flexibility

**Comment by vsouza** [comment]
Thanks @lordent for this fix.

If you feel comfortable you can send a pull request with this fix.

Thank you.
